### ISSUE TITLE
is it only for english and mandarin?

### ISSUE THREAD

**Issue by A-d-DASARE** [roedoejet/FastSpeech2#3]
can it be trained with any language? or specific to mentioned languages? and how to prepare lexicon for a new language?

**Comment by roedoejet** [comment]
No, you can use it for a new language, see the steps here: https://github.com/roedoejet/FastSpeech2#adding-a-new-language. Building a lexicon if it doesn't already exist is a non-trivial task depending on the transparency between the orthography and the pronunciation form for your language. You can see the files here: https://raw.githubusercontent.com/roedoejet/FastSpeech2/master/lexicon/ for examples of the formatting of the lexicon, or you can develop letter-to-sound rules with the https://github.com/roedoejet/g2p package which is already integrated here.

**Comment by A-d-DASARE** [comment]
Thanks! will check it out. But this link does not seem to be available https://raw.githubusercontent.com/roedoejet/FastSpeech2/master/lexicon/ any other alternatives?

**Comment by roedoejet** [comment]
Sorry, yes, here: https://github.com/roedoejet/FastSpeech2/tree/master/lexicon
